# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Configuration Name')),
                ('config_file', models.FileField(upload_to='configs', verbose_name='Configuration File')),
                ('input_type', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'WORD'), ('HTML', 'HTML')], max_length=4, verbose_name='Expected Extension')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Converted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readied', models.FileField(upload_to='converted', verbose_name='Converted File')),
                ('config_used', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='extractedAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_file', models.FileField(upload_to='answers', verbose_name='Extracted File')),
            ],
        ),
        migrations.CreateModel(
            name='toConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Document Name')),
                ('candidate', models.FileField(upload_to='ready_convert', verbose_name='Document')),
                ('extension', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'WORD'), ('HTML', 'HTML')], max_length=4)),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='extractedanswers',
            name='extracted_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doccon2.toConvert'),
        ),
        migrations.AddField(
            model_name='converted',
            name='converted_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doccon2.toConvert'),
        ),
    ]
