# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccon2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedanswers',
            name='solr_added',
            field=models.CharField(choices=[('YES', 'Y'), ('NO', 'N')], default='N', max_length=3, verbose_name='Added to Solr'),
        ),
    ]
